-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, 
    CONCAT(u.CITY,' ',u.STREET_ADDRESS1,' ',u.STREET_ADDRESS2) as '전체주소',
    CONCAT(LEFT(u.TLNO,3),'-',SUBSTRING(u.TLNO,4,4),'-',RIGHT(u.TLNO,4)) as 전화번호
FROM USED_GOODS_BOARD as b
JOIN USED_GOODS_USER as u
ON b.WRITER_ID = u.USER_ID
GROUP BY u.USER_ID
HAVING COUNT(*) >=3
ORDER BY 1 DESC
