-- 코드를 입력하세요
WITH REVIEWS AS (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) as AVG_SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
)

SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, r.AVG_SCORE as SCORE
FROM REST_INFO as i
JOIN REVIEWS as r
ON i.REST_ID = r.REST_ID
WHERE i.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC