-- 코드를 입력하세요
SELECT h.HISTORY_ID,
CASE
    WHEN DATEDIFF(h.END_DATE,h.START_DATE)+1 >= 90 THEN 
        ROUND(c.DAILY_FEE*(DATEDIFF(h.END_DATE,h.START_DATE)+1)*(1-(
            SELECT p.DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN as p
            WHERE p.CAR_TYPE = c.CAR_TYPE
            AND p.DURATION_TYPE = '90일 이상')/100),0)
    WHEN DATEDIFF(h.END_DATE,h.START_DATE)+1 >= 30 THEN 
        ROUND(c.DAILY_FEE*(DATEDIFF(h.END_DATE,h.START_DATE)+1)*(1-(
            SELECT p.DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN as p
            WHERE p.CAR_TYPE = c.CAR_TYPE
            AND p.DURATION_TYPE = '30일 이상')/100),0)
    WHEN DATEDIFF(h.END_DATE,h.START_DATE)+1 >= 7 THEN 
        ROUND(c.DAILY_FEE*(DATEDIFF(h.END_DATE,h.START_DATE)+1)*(1-(
            SELECT p.DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN as p
            WHERE p.CAR_TYPE = c.CAR_TYPE
            AND p.DURATION_TYPE = '7일 이상')/100),0)
    ELSE
        c.DAILY_FEE*(DATEDIFF(h.END_DATE,h.START_DATE)+1)
    END AS FEE 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
JOIN CAR_RENTAL_COMPANY_CAR as c
ON h.CAR_ID = c.CAR_ID
WHERE c.CAR_TYPE='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
