-- 코드를 입력하세요
SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT as a
JOIN DOCTOR as d
ON a.MDDR_ID = d.DR_ID
JOIN PATIENT as p
ON p.PT_NO = a.PT_NO
WHERE a.APNT_CNCL_YN = 'N'
AND DATE(a.APNT_YMD) = '2022-04-13'
ORDER BY a.APNT_YMD