-- 코드를 입력하세요
SELECT HOUR(DATETIME) as 'HOUR', COUNT(*) as 'COUNT'
FROM ANIMAL_OUTS as a
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
# HAVING HOUR(DATETIME) BETWEEN 9 AND 19
ORDER BY 1