# -- 코드를 작성해주세요
# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS
# WHERE SKILL_CODE &(SELECT CODE FROM SKILLCODES WHERE NAME='Python')
# = (SELECT CODE FROM SKILLCODES WHERE NAME='Python')
# OR SKILL_CODE &(SELECT CODE FROM SKILLCODES WHERE NAME='C#')
# = (SELECT CODE FROM SKILLCODES WHERE NAME='C#')
# ORDER BY ID ASC

SELECT DISTINCT
       d.ID,
       d.EMAIL,
       d.FIRST_NAME,
       d.LAST_NAME
FROM DEVELOPERS d
JOIN SKILLCODES s
  ON (d.SKILL_CODE & s.CODE) > 0
WHERE s.NAME IN ('Python', 'C#')
ORDER BY d.ID;

