-- 코드를 작성해주세요
WITH MAX_TABLE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
    (m.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM ECOLI_DATA as e
JOIN MAX_TABLE m
ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR, YEAR_DEV